### ISSUE TITLE
Feature request: Disable ACL copying / checking

### ISSUE THREAD

**Issue by godeater** [lkarlslund/fastsync#1]
Hi there,

Not sure if you're open for feature requests at all - but if you are, I'd like to request the ability to disable the check / copy of ACLs on the source system. 

I've been using fastsync to copy a load of stuff from my old home server to its newer replacement - and whilst the data appears to be making it over just fine (and as fast as my poor old home server can shove it down the wire!), the client side is reporting "Error getting ACL for <every single file>".  I'm not sure if this is because the file source system doesn't support them (it's btrfs), or just that they don't have any ACLs, (or whether maybe I should be running the server part as root?) but it seems like a lot of extra noise in the client output that could be avoided if there was a way to toggle that feature off?

Anyway - thanks for a great tool - in all other respects it's awesome for me!

**Comment by lkarlslund** [comment]
Just committed :-)
